### ISSUE TITLE
Edit status line

### ISSUE THREAD

**Issue by kamushadenes** [gpakosz/.tmux#10]
Hello there!

How can I add/remove things to the status line in a way that doesn't break everything?

Adding modifications to .tmux.conf.local not only completely overrides everything, but is also overriden in the next second by the default

**Comment by gpakosz** [comment]
Currently, the theme doesn't offer customization points beside the various `tmux_conf_theme_xxx` variables.

Can you give more details about what customization would you like to achieve?

**Comment by kamushadenes** [comment]
Hello gpakosz!

Thanks for replying.

I'm willing to include CPU usage and load average, as well as making the battery indicator a percentage instead of a bar, and would also like to display network speed.

Could you give an example on modifying the script to achieve this? This way I could fork the project and maybe submit a pull request if I manage to do it.

**Comment by gpakosz** [comment]
I pushed the `wip-battery-percentage` branch. You now can use `tmux_conf_battery_style=percentage` in your `.tmux.conf.local` file.

About CPU usage and load average and network speed I don't really know how to guide you. Those indicators won't enter the master branch unless they work reliably for Linux, Mac and Cygwin.

From there, I'm wondering how I can provide a reliable way of hooking the right part of the status line. My initial idea would be to offer a `tmux_conf_theme_status_right` in which you could insert hooks but at that point it raises many questions:

- that `tmux_conf_theme_status_right` would require proper shell quoting because you want everything in there 
- `.tmux.conf.local` needs to be modified with the same heredoc trick as `.tmux.conf` so that you can run custom code
- the current code hardcodes the insertion of separators depending on which indicator is enabled. You can't really shuffle the indicators around without breaking foreground colors, background colors and separators

That being said, if you're ok your network load and CPU load indicators are hardcoded to be between battery and time, then try the `wip-status-right-custom-segment` branch which starts from the `wip-battery-percentage` branch.

Hope that helps

**Comment by gpakosz** [comment]
FYI, I removed the `wip-battery-percentage` branch as it's now available in the main line
