### ISSUE TITLE
Powerline Logs

### ISSUE THREAD

**Issue by jnreynoso** [gpakosz/.tmux#101]
I have been using tmux since a while now, and I decided to connect remotely through ssh (windows bash) with a terminal emulator (Cmder), and I am getting the following registry messages.

Additional Info:

System Operative: Windows 10 Pro (Using Bash)
Terminal Emulador: Cmder

![tmux conf](https://user-images.githubusercontent.com/8073456/29097862-ca2a8faa-7c61-11e7-8f8f-a8f20879fbe2.png)

**Comment by gpakosz** [comment]
Hello @jnreynoso,

So you're running tmux in Bash on Windows (WSL), using Cmder as a terminal emulator and you're sshing into another box?

Usually, "duplicated" status line happens when the terminal emulator and tmux disagree on Unicode character width.

I never tried Cmder but it's using ConEmu under the hood, which is just a Windows console wrapper and Windows console doesn't support colors correctly which can also be seen in your screenshot. See https://github.com/gpakosz/.tmux#troubleshooting where I recommend using wsltty.

Finally, I'm not sure how the message asking you to activate windows participates in the problem.

**Comment by jnreynoso** [comment]
I initially opened a tmux session on my desktop (where I have an ultrawide monitor), when I connect from my laptop which has a smaller screen the messages appear

```bash
  $ ssh user@host -t tmux a
```
but if I connect via ssh and then start a tmux session, the messages will not be displayed again.

```bash
  $ ssh user@host
  $ tmux
```
In my opinion the problem is given by the difference in the width of the monitors

Anyway thank you very much.

**Comment by gpakosz** [comment]
> when I connect from my laptop which has a smaller screen the messages appear

Which message exactly?

**Comment by jnreynoso** [comment]
The ones I show in the screenshot!

**Comment by gpakosz** [comment]
I see 3 things in the screenshot:
  - buggy colors (you may want to set all `_attr` variables to `'none'` in your `~/.tmux.conf.local` copy
  - a status line bug: the status line is repeated, which usually indicates a discrepancy between the Unicode standard version supported by the host that runs tmux and version used by the terminal emulator itself
  - the Windows activation message (which now I believe is not what you're after)

**Comment by jnreynoso** [comment]
a status line bug, I am talking about these messages
![tmux-message](https://user-images.githubusercontent.com/8073456/29140563-819b7498-7d10-11e7-96fc-6c2a639e9569.png)

**Comment by gpakosz** [comment]
I'm afraid you will have to seek help from ConEmu author.

In the meantime, not using Powerline symbols will likely help.

**Comment by jnreynoso** [comment]
When I connect and then start tmux, the same thing does not happen

```bash
  $ ssh user@localhost
  $ tmux
```
![tmux-other](https://user-images.githubusercontent.com/8073456/29140812-6a8875d4-7d11-11e7-9dee-e0068ffd3702.png)

thank you!
