### ISSUE TITLE
Why can not I apply this theme

### ISSUE THREAD

**Issue by lnxiaoy** [gpakosz/.tmux#11]
I follow your steps, and nothing happened, may i ask why your file with "#", does it makes any sence?

**Comment by gpakosz** [comment]
Hello,

Make sure you stop all tmux client and server processes.

Backup your existing `.tmux.conf` file and try again following the installation steps as per documented in `README.md`:

    $ cd
    $ rm -rf .tmux
    $ git clone https://github.com/gpakosz/.tmux.git
    $ ln -s .tmux/.tmux.conf
    $ cp .tmux/.tmux.conf.local .

About your "may i ask why your file with "#", does it makes any sence?" question, I'm not sure I understand what you're referring to.

In both Bash and tmux, `#` starts a comment and comment lines are ignored. Now there's a trick:

- the first line of `.tmux.conf` starts with `# cat << ►_◄ > /dev/null` and later in the file there's a line starting with `# ►_◄`. Those lines are both ignored by tmux, because they start with a `#`
- below the line starting with `# ►_◄`, all lines start with `# ` and they will be ignored by tmux as well
- pay attention that those comment lines are in fact a whole shell script put behind comments, and it's important to notice all the lines start with `#` followed by a space.
- now if you run the `cut -c3- ~/.tmux.conf` command, you notice that it takes `~/.tmux.conf` and removes the first 2 columns of the file
- removing the first 2 columns of the file transforms the valid tmux configuration file into a valid shell script
- when you pipe the result of `cut -c3- ~/.tmux.conf` to `sh`, your shell evaluates the `cat << ►_◄ > /dev/null` statement
  - remember, `cut -c3-` removed the first 2 columns, hence it removed the `#` characters
  - `cat << ►_◄ > /dev/null` is a classic [HEREDOC](http://tldp.org/LDP/abs/html/here-docs.html), I just used fancy Unicode characters
  - when your shell evaluates the `cat << ►_◄ > /dev/null` statement, the practical effect is to ignore now truncated tmux configuration lines before evaluating what was before a commented shell script (remember `cut -c3-` removed the comments)

Hope that sheds some light to how it works.

**Comment by lnxiaoy** [comment]
Thank you for answering my question, my English is very poor, thank you for your patience;
now, I try this: 
  1. I change into TMUX mode, and type Ctrl + b + m, and it displays "mouse mode : on", it seems it does work
  2. but i run "cut -c3- ~/.tmux.conf | sh -s apply_configuration" it displays "unkwon opration pane-borde-style"
can you help me to fix this? thank you very much, i'm not get used to markdown.......

**Comment by gpakosz** [comment]
Which version of tmux are you using?

My configuration only works with tmux `1.9`, `2.0` or `2.1+` . If you use tmux `1.9` or `2.0`, use the corresponding branch of the configuration.

**Comment by lnxiaoy** [comment]
I did it!  I just use vertion 1.8, so,I update to lastest version , your configure have shown, thank you very much
