### ISSUE TITLE
Feature request: git info

### ISSUE THREAD

**Issue by githorse** [gpakosz/.tmux#133]
Tmux newbie. I'd like to see git branch/status info in my statusline if I'm in a git repo. I tried using the [tmux-gitbar](https://github.com/aurelien-rainone/tmux-gitbar) plugin but this statusbar seems to overwrite it. Is there some way to make them play nice? Alternatively, would it be possible to add git info as an optional statusbar segment?

**Comment by gpakosz** [comment]
Hello @githorse,

For the moment I don't plan to add new segments for this. Most shells come with their `__git_ps1` equivalent and I don't believe it's worth reimplementing that.

**Comment by githorse** [comment]
Understood. On my end, I take it integrating a an existing plugin like tmux-gitbar with your statusbar is non-trivial?

**Comment by gpakosz** [comment]
I know nothing about `tmux-gitbar`. It seem to be based on `tpm` which I don't want to support because I believe it defeats the purpose of my configuration that tries hard to be standalone (no external scripts etc...). Have a look at issues #114 and #61.

As far as Git status and branch information are concerned, I believe these clues should be displayed by the prompt. Because having them displayed by tmux means there's always lag behind because they update only when tmux refreshes the status bar.

Cheers

**Comment by gpakosz** [comment]
> It seem to be based on tpm which I don't want to support 

Well the reality is that tpm is not smart enough when discovering which files are being sourced. Typically:
```
if '[ -f ~/.tmux.conf.local ]' 'source ~/.tmux.conf.local'
```

If tpm understood this line, it would be easy to add tpm instructions at the end of your `~/.tmux.conf.local` copy. And have both of our projects live together happily.

When I eventually drop support for tmux `2.2`, I can use `source-file -q` instead of `if-shell` and then tpm may work automagically if it has not been fixed/improved in the meantime.

**Comment by githorse** [comment]
Thanks @gpakosz -- I'll check back in a while and see if `source-file-q` fixes it. Not too worried about it since, as you point out, the information's already available in my prompt. (But still would be cool.)
