### ISSUE TITLE
The status bar is not rendering properly

### ISSUE THREAD

**Issue by kmer1224** [gpakosz/.tmux#142]
As the following image, the status bar is not rendering properly (there a black block at rightmost).

<img width="1280" alt="screen shot 2018-03-08 at 09 44 36" src="https://user-images.githubusercontent.com/13390788/37128479-57a0168a-22b5-11e8-8514-6ba86caceb88.png">

In Vim, the vim status bar is also not rendering properly. The length is less than the screen width.

<img width="1280" alt="screen shot 2018-03-08 at 09 54 25" src="https://user-images.githubusercontent.com/13390788/37128987-b59e0bc8-22b7-11e8-9336-61d20e1ed740.png">

I tried to empty `theme_status_right` and  remain session name in `theme_status_left`:

<img width="1280" alt="screen shot 2018-03-08 at 09 39 33" src="https://user-images.githubusercontent.com/13390788/37129033-e5089036-22b7-11e8-9948-851372d75d32.png">

<img width="1280" alt="screen shot 2018-03-08 at 00 18 36" src="https://user-images.githubusercontent.com/13390788/37129037-eaa3b926-22b7-11e8-91f2-1632359e2901.png">

My environments are:
* macOS High Sierra 10.13.3
* zsh (oh-my-zsh)
* iTerm2 Build 3.1.5 (`Use Unicode Version 9 Widths` is *dsiabled*)
* tmux 2.6

**Comment by gpakosz** [comment]
Hello @kmer1224,

Unfortunately, this is something that may happen depending on your combination of fonts, terminal emulator and the choice of unicode symbols you make.

For a start, you may want to confirm stock tmux configuration is not subject to the problem by running:
```
$ tmux -S test -f /dev/null
```

I believe even the stock configuration will exhibit your problem based on your second screenshot: here you can see even vim stops rendering its status line "one block too early". This is likely due to the last column is not large enough to render a character at the font size you chose.

**Comment by kmer1224** [comment]
Hi,

Sorry for my late reply.

Yes, you're right. Vim still stops rendering its status line one block too early by running:
```
$ tmux -S test -f /dev/null
```
But if i use vim without tmux, its status line is rendering properly.
Now, I using lightline.vim instead of vim-airline, and the vim status line is rendering properly.

But the rightmost in the tmux status line, it still a black block here, I don't know why.

**Comment by gpakosz** [comment]
@kmer1224 

tmux 2.7 has been released and in the change log there's
> * Correctly remove padding cells to fix a UTF-8 display problem (GitHub issue 1090).

**Comment by gpakosz** [comment]
@kmer1224 

Hello. Did you upgrade to tmux 2.7 since you opened this issue? Does it improve things for you?

**Comment by kmer1224** [comment]
@gpakosz 

Hi! Yes, I upgraded my tmux to 2.7. The status bar is rendering properly. Thanks you.
