### ISSUE TITLE
No zoom indicator

### ISSUE THREAD

**Issue by kleinjm** [gpakosz/.tmux#147]
Not sure if you'd consider this a bug or an issue but I don't see a zoom icon in the status bar when expanding a pane to the entire window.
Command: prefix + z
Default tmux behavior: adds a `*Z` to status bar for the current window

**Comment by gpakosz** [comment]
Hello @kleinjm,

This is because `prefix + z` is bound to my own maximize window feature:
  - this feature predates stock maximize window feature
  - on the upside, you get a maximized window that you can further split
  - on the downside you lose the maximized flag

I'll have a loot at whether I can do something for it.

**Comment by rhcarvalho** [comment]
Hi!

I was looking for a solution to this, and I found that you can uncomment two lines in `.tmux.conf.local` to achieve that:

1. [`tmux_conf_theme_window_status_format='#I #W#{?window_bell_flag,🔔,}#{?window_zoomed_flag,🔍,}'`](https://github.com/gpakosz/.tmux/blob/2b0cb0b43ce7b4d212d91415390db8faf1b421df/.tmux.conf.local#L116)
2. [`tmux_conf_theme_window_status_current_format='#I #W#{?window_zoomed_flag,🔍,}'`](https://github.com/gpakosz/.tmux/blob/2b0cb0b43ce7b4d212d91415390db8faf1b421df/.tmux.conf.local#L131)

Alternatively, you can add `#F` to the format string, that's Tmux window flags like `*Z` (can be found in `man tmux` for reference, together with other variables that can be used).

**Comment by kleinjm** [comment]
That's exactly what I was looking for, thanks @rhcarvalho!
