### ISSUE TITLE
Sending ^a to screen inside of tmux

### ISSUE THREAD

**Issue by mamercad** [gpakosz/.tmux#152]
There are times when I run screen inside of a tmux window, but with your configuration, I can't seem to figure out how to send the screen session ^a (in the past, ^a followed by ^a would pass it to the inner session).

**Comment by gpakosz** [comment]
Hello @mamercad,

My configuration indeed uses <kbd>CTRL</kbd>+<kbd>a</kbd> but hitting it twice should send it to the underlying program.

You can confirm that by running `cat` in a tmux pane and hitting <kbd>CTRL</kbd>+<kbd>a</kbd> twice:
  1. the first time the prefix indicator will show up
  2. the second time the key "events" are sent to the underlying program, `cat`, which displays `^A`

As for why `screen` doesn't grab it, I quite don't know because it seems to work for me! (tried it even though I'm not a screen user).

Maybe try to verify you didn't override my bindings:
```
$ tmux list-keys | grep C-a
bind-key    -T copy-mode    C-a               send-keys -X start-of-line
bind-key    -T prefix       C-a               send-prefix -2
```
The second line is what sends <kbd>CTRL</kbd>+<kbd>a</kbd> to the underlying program.

Hope that helps.

**Comment by mamercad** [comment]
Ah, figured it out, thanks for the helpful hints, `bind-key C-a last-window` (my customization) was breaking this for me.
