### ISSUE TITLE
Why comment out all those functions ? which cause maximize-pane fail

### ISSUE THREAD

**Issue by DravenJohnson** [gpakosz/.tmux#154]
throw `'cut -c3- ~/.tmux.conf | sh -s maximize_pane' returned 127` first
then `'cut -c3- ~/.tmux.conf | sh -s maximize_pane' returned 2` again after I uncommented the function

What's the reason start from [here](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L171) everything is comment out? When i [use + sign to maximize pane](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L79), it won't work anymore.

**Comment by DravenJohnson** [comment]
Sorry i was misunderstanding to those "comment" sign `#`, i think it's how tmux config works.

Then this bring up the question again, why `<prefix> +` doesn't work anymore?
return error code 127: `cut -c3- ~/.tmux.conf | sh -s maximize_pane' returned 127`

**Comment by gpakosz** [comment]
Hello @DravenJohnson,

It seems to me you pulled the repository while not sourcing `~/.tmux.conf` again. Can you confirm you're still having a problem after having killed all tmux processes and relaunched?

**Comment by DravenJohnson** [comment]
Hi @gpakosz, Well, you are right. i am pretty new to tmux :P
Since my tmux is running all the time, I totally forget to reload it after config update.

Thank you so much for the help, you may close this issue. Sorry for the inconvenience.

**Comment by gpakosz** [comment]
@DravenJohnson 

No worry. See https://github.com/gpakosz/.tmux/issues/11#issuecomment-166112867 for an explanation of how this `.tmux.conf` is both a valid tmux configuration and a valid shell script.

What you experienced is a binding trying to call the `maximize_pane()` shell function but I've renamed it to `_maximize_pane()` since then.

Hope that helps.
