### ISSUE TITLE
Disable a certain shortcut

### ISSUE THREAD

**Issue by tmihai20** [gpakosz/.tmux#186]
Hello. First of all, please do not stick and stone me. I found your project online and I am enjoying tmux a lot more because of this tiny, but very important .tmux.conf. One single thing bothers me, where should I look to disable a certain shortcut? I went over it a few times, but I really do not know where to look. I want to disable CTRL+a+x, because it overwrites any combination with kill-pane.

**Comment by gpakosz** [comment]
Hi @tmihai20 👋

I don't think I understand "because it overwrites any combination with kill-pane":
  - do you want to stop using <kbd>CTRL</kbd> + <kbd>A</kbd> as a prefix for all bindings
  - do you want to disable the binding that kills panes?

In any case, you should override the default behavior in your `~/.tmux.conf.local` copy.
For instance, you can add
```
unbind -T prefix x
```

**Comment by tmihai20** [comment]
Thank you for replying. I would like to disable the binding that kills a pane. I will try unbinding the prefix x binding.

**Comment by gpakosz** [comment]
```
set -gu prefix2
```

**Comment by tmihai20** [comment]
That did the trick. I had tried unbind -T prefix C-a, but it did not disable the shortcut and unbind -T prefix x, but it did not let me use CTRL+A at all.
