### ISSUE TITLE
Cannot set pane border

### ISSUE THREAD

**Issue by goofansu** [gpakosz/.tmux#22]
I added following lines in `~/.tmux.conf.local` to change border color, but it does not take effect, am I missing anything?

```
set -g pane-border-fg green
set -g pane-border-bg black
set -g pane-active-border-fg white
set -g pane-active-border-bg yellow
```

**Comment by gpakosz** [comment]
Hi there,

Please edit `~/.tmux.conf.local` and add

```
tmux_conf_theme_pane_border_fg=green
tmux_conf_theme_pane_border_black=green
tmux_conf_theme_pane_active_border_fg=white
tmux_conf_theme_pane_active_border_bg=yellow
```

The reason it's not working the way you tried is because `~/.tmux.conf.local` is sourced before the theme is being applied.

Variables for configuring the theme's look&feel exist but are currently not documented because I'm not quite sure how I want to expose them yet.

Sorry for the inconvenience.

**Comment by goofansu** [comment]
Thanks, `tmux_conf_theme_pane_border_black=green` should be `tmux_conf_theme_pane_border_bg=black` 😃 

Another question, how to make the border bold, like the picture:

![image 7](https://cloud.githubusercontent.com/assets/1143191/16629287/d5780440-43e7-11e6-9a20-f61cf4b34c68.png)

**Comment by gpakosz** [comment]
You may want to uncomment [this line](https://github.com/gpakosz/.tmux/blob/5156c9fe23c3460c2947888ce5ce7b6db7b44deb/.tmux.conf#L182), as I said it's really rough at the moment :/

**Comment by goofansu** [comment]
@gpakosz Thanks. Don't worry, I think the default theme is good enough.
