### ISSUE TITLE
change mouse scrolling speed ?

### ISSUE THREAD

**Issue by souhaiebtar** [gpakosz/.tmux#231]
is there a way to change the scrolling speed (number of line when scrolling) ? 
thanks anyway

**Comment by gpakosz** [comment]
Hello @souhaiebtar 👋

If you do
```
$ tmux list-keys | grep Wheel
bind-key    -T copy-mode    WheelUpPane       select-pane ; send-keys -X -N 5 scroll-up
bind-key    -T copy-mode    WheelDownPane     select-pane ; send-keys -X -N 5 scroll-down
bind-key    -T copy-mode-vi WheelUpPane       select-pane ; send-keys -X -N 5 scroll-up
bind-key    -T copy-mode-vi WheelDownPane     select-pane ; send-keys -X -N 5 scroll-down
bind-key    -T root         WheelUpPane       if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= \"#{pane_in_mode}\" \"send-keys -M\" \"copy-mode -et=\""
bind-key    -T root         WheelUpStatus     previous-window
bind-key    -T root         WheelDownStatus   next-window
```

You see that `WheelUpPane` and `WheelDownPane` are classical bindings.
You can e.g. increase the speed by adding the following to your `~/.tmux.conf.local` copy
```
bind-key    -T copy-mode    WheelUpPane       select-pane ; send-keys -X -N 7 scroll-up
bind-key    -T copy-mode    WheelDownPane     select-pane ; send-keys -X -N 7 scroll-down
bind-key    -T copy-mode-vi WheelUpPane       select-pane ; send-keys -X -N 7 scroll-up
bind-key    -T copy-mode-vi WheelDownPane     select-pane ; send-keys -X -N 7 scroll-down
```

**Comment by souhaiebtar** [comment]
@gpakosz when adding those line, no current target

**Comment by gpakosz** [comment]
@souhaiebtar Did you reload tmux config after changing your `~/.tmux.conf.local` copy?

**Comment by souhaiebtar** [comment]
yes i did, those line just appear when launching tmux the first time, they disapear just by pressing enter

**Comment by gpakosz** [comment]
Oh yeah you have to escape `;`

```
bind-key    -T copy-mode    WheelUpPane       select-pane \; send-keys -X -N 7 scroll-up
bind-key    -T copy-mode    WheelDownPane     select-pane \; send-keys -X -N 7 scroll-down
bind-key    -T copy-mode-vi WheelUpPane       select-pane \; send-keys -X -N 7 scroll-up
bind-key    -T copy-mode-vi WheelDownPane     select-pane \; send-keys -X -N 7 scroll-down
```

**Comment by souhaiebtar** [comment]
@gpakosz  thanks 👍

**Comment by xiaotianxt** [comment]
Hi, thanks for your kind instruction on every issue, it's such a lucky thing to know your open-source project.

I’m using a touchpad on macOS, but the scrolling behavior in tmux is not satisfying. Specifically, I want responsive acceleration when scrolling fast. For example, when quickly flicking with my fingers, I’d like to scroll rapidly to the top of the shell. Before using tmux, this worked naturally due to macOS’s native scroll acceleration. However, in tmux, the WheelUpPane and WheelDownPane events seem to scroll linearly, making the experience less responsive. Is there a way to add scroll acceleration in tmux for a more intuitive scrolling experience?

**Comment by gpakosz** [comment]
@xiaotianxt You would need to reach out to the tmux project for this
