### ISSUE TITLE
Got these errors after installing it today.

### ISSUE THREAD

**Issue by Mahmoudz** [gpakosz/.tmux#25]
It's working fine! but when I source the config file I get this:

```
❯ . ~/.tmux.conf
/Users/mz/.tmux.conf:8: command not found: setw
/Users/mz/.tmux.conf:14: command not found: bind
/Users/mz/.tmux.conf:19: command not found: bind
/Users/mz/.tmux.conf:22: command not found: bind
/Users/mz/.tmux.conf:534: parse error near `\n'
```

**Comment by gpakosz** [comment]
Why are you sourcing `~/.tmux.conf` from your shell session?

**Comment by Mahmoudz** [comment]
@gpakosz what's the alternative to make it work?

**Comment by gpakosz** [comment]
I'm not sure to understand what you have in mind by "make it work". What are you trying to achieve exactly?

**Comment by Mahmoudz** [comment]
I thought when making change to the default configuration (example: add `set -g mouse on` to the `.tmux.conf.local` file), it wouldn't take place unless I source the config file `.tmux.conf` file using `. ~/.tmux.conf`.

However, after your message I tried making changes without sourcing the file. Just closing and opening tmux. This just worked! (means the changes were taken).

Thanks.

**Comment by innomation** [comment]
As mentioned in the documentation:
"Instead of altering the ~/.tmux.conf file and diverging from upstream, the proper way is to edit the ~/.tmux.conf.local file:"

**Comment by gpakosz** [comment]
Oh alright.

Well the way I made it work is `~/.tmux.conf` sources `~/.tmux.conf.local` as in [`tmux source ~/tmux.conf.local`](https://github.com/gpakosz/.tmux/blob/5156c9fe23c3460c2947888ce5ce7b6db7b44deb/.tmux.conf#L142). The idea behind splitting things between `~/.tmux.conf` and `~/.tmux.conf/local` is to be able to `git pull` and get an update without having to resolve conflicts would you have configured/customized this configuration.

By default, [`<prefix> e`](https://github.com/gpakosz/.tmux/blob/5156c9fe23c3460c2947888ce5ce7b6db7b44deb/.tmux.conf#L19) will open `~/.tmux.conf.local` with the editor configured with the `$EDITOR` environment variable. When the editor closes, `~/.tmux.conf` gets sourced again and it turns sources `~/.tmux.conf.local` in which modifications were just made. 

When I say "source", it's `tmux source`. This is different from asking your shell to source another shell script fragment.

To give you the big picture, I'm using a trick to make `~/.tmux.conf` **both a `tmux` configuration file and a shell script**:
  - when `tmux` reads `~/.tmux.conf`, it treats every line starting with `#` as a comment. This effectively means that [the end of `~/.tmux.conf`](https://github.com/gpakosz/.tmux/blob/5156c9fe23c3460c2947888ce5ce7b6db7b44deb/.tmux.conf#L150-L533) is totally invisible to `tmux`
  - however, when you pipe the output of `cut -c3- ~/.tmux.conf` to `sh`, then `sh` evaluates `cat << ►_◄ > /dev/null` and skips all the `tmux.conf` file content until it reaches the [`►_◄`](https://github.com/gpakosz/.tmux/blob/5156c9fe23c3460c2947888ce5ce7b6db7b44deb/.tmux.conf#L150) heredoc marker. I used `►_◄` because it looks funny but generally people use `EOF` as heredoc marker

Back to your original question, when you do `. ~/.tmux.conf` you're telling your shell to interpret the `~/.tmux.conf` file as a shell script, **which it's not**. And the error message you're getting is expected: `setw` is nor a command nor a shell builtin.

Hope that sheds some light on what's going on :)
