### ISSUE TITLE
unable to change background color in ubuntu 19.04

### ISSUE THREAD

**Issue by thebeastxdxd** [gpakosz/.tmux#268]
![tmux_color_problems](https://user-images.githubusercontent.com/16572680/61960341-f11ee100-afcd-11e9-83ed-2cebd857eca9.PNG)
After installing the configuration on an almost clean ubuntu 19.04,
the status bar appears at the top and the terminal keeps the default terminal color.
The TERM var outside tmux is xterm-256color, and inside its screen-256color.
Except for that i didnt change anything.
If I didn't miss anything I am assuming i should see the theme you set
and also the status bar should be at the bottom.

**Comment by gpakosz** [comment]
Hello @thebeastxdxd 

> the status bar appears at the top

That's because you uncommented `set -g status-position top` in your `~/.tmux.conf.local` copy.

> the terminal keeps the default terminal color

I'm not sure what you're referring to when you say that.

Instead of using `set -g window-style` and `set -g window-active-style`, you must edit your `~/.tmux.conf.local` copy and configure:
  - `tmux_conf_theme_window_fg`
  - `tmux_conf_theme_window_bg`
  - `tmux_conf_theme_focused_pane_fg`
  - `tmux_conf_theme_focused_pane_bg`

Hope that helps!

**Comment by jSadm** [comment]
Same question as @thebeastxdxd , how can i config `set -g status-bg`?
