### ISSUE TITLE
Status line is broken in panes synchronized mode.

### ISSUE THREAD

**Issue by Kur0x** [gpakosz/.tmux#290]
When I enable synchronize mode, cursor can run into the status bar. And status bar will be duplicated when time update. Status bar become part of the input area.
![image](https://user-images.githubusercontent.com/9768369/66802902-9ce22800-ef50-11e9-88c4-4c58e2ad8b20.png)

**Comment by gpakosz** [comment]
Hello @Kur0x 👋

The problem your facing is described in `README.md`: https://github.com/gpakosz/.tmux#troubleshooting and depends on your combination of tmux, libc and terminal versions.

Likely, `set synchronize-panes` exacerbates the issue but it's not caused by it.
I'm sure if you stop using Powerline symbols the problem will stop.

**Comment by Kur0x** [comment]
Hi, @gpakosz 
I think it's not the Powerline symbols issue. The problem still appeares, when I stoped using it.
![image](https://user-images.githubusercontent.com/9768369/66880817-17fe1980-eff7-11e9-8345-24326bbf5714.png)

I found the reason.
The default synchronized indicator cause the problem.
```
# synchronized indicator
tmux_conf_theme_synchronized='🔒'     # U+1F512
```

**Comment by gpakosz** [comment]
Hey @Kur0x 👋

I'm sorry I was in a hurry yesterday. I should have thought of `tmux_conf_theme_synchronized`. I'll likely replace the default value with something else.
