### ISSUE TITLE
WSL2 - Powerline bar doesn't show correctly the fonts

### ISSUE THREAD

**Issue by lucamaraschi** [gpakosz/.tmux#294]
Using Windows Terminal (Version: 0.6.2951.0) with the standard settings in `.tmux.conf.local` and the patched version of `CascadiaCode Nerd Font` Powerline doesn't show correctly.
<img width="1265" alt="Annotation 2019-11-03 231741" src="https://user-images.githubusercontent.com/332968/68104528-40f42a80-fe90-11e9-82c3-bc0418136e71.png">

**Comment by Kira-Lappo** [comment]
I didn't get what the issue is. I use WSL 1 (via Windows Terminal app) and `Cascadia Mono PL` font, and the status bar is shown fine as to me.
![image](https://user-images.githubusercontent.com/11411852/71090777-dd5e5c00-21b4-11ea-9d41-9365ce478835.png)

**Comment by gpakosz** [comment]
Hello @lucamaraschi 👋

When you say
> with the standard settings in `.tmux.conf.local`

I understand that you didn't edit your copy to uncomment:
```
tmux_conf_theme_left_separator_main='\uE0B0'  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub='\uE0B1'   #   you only need fonts patched with
tmux_conf_theme_right_separator_main='\uE0B2' #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub='\uE0B3'  #   PowerlineSymbols.otf font, see README.md
```

In which case it's fairly normal if you don't see the Powerline symbols

**Comment by tianxingyang** [comment]
> Hello @lucamaraschi 👋
> 
> When you say
> 
> > with the standard settings in `.tmux.conf.local`
> 
> I understand that you didn't edit your copy to uncomment:
> 
> ```
> tmux_conf_theme_left_separator_main='\uE0B0'  # /!\ you don't need to install Powerline
> tmux_conf_theme_left_separator_sub='\uE0B1'   #   you only need fonts patched with
> tmux_conf_theme_right_separator_main='\uE0B2' #   Powerline symbols or the standalone
> tmux_conf_theme_right_separator_sub='\uE0B3'  #   PowerlineSymbols.otf font, see README.md
> ```
> 
> In which case it's fairly normal if you don't see the Powerline symbols

I still have similar problem after uncomment those.
![image.png](https://i.loli.net/2020/02/01/za5KUDtdk7Z92Xm.png)
![image.png](https://i.loli.net/2020/02/01/1QfdY9lBzHT3PgJ.png)

**Comment by Kira-Lappo** [comment]
@tianxingyang so what is exactly wrong with your status bar? It looks fine as to me talking about powerfont symbols.

**Comment by tianxingyang** [comment]
> @tianxingyang so what is exactly wrong with your status bar? It looks fine as to me talking about powerfont symbols.

I'm not sure if the your battery logo is default setting or not?

**Comment by Kira-Lappo** [comment]
@tianxingyang 
ok, here we go, ultimate oh-my-tmux installation from scratch

1. By default tmux looks like this. Font: Courier New
![2020-02-01_11-43-03](https://user-images.githubusercontent.com/11411852/73589573-f1ea7f80-44e8-11ea-9270-f53eb166f052.png)

1. After installing oh-my-tmux by steps from README file. Font: Courier New
![2020-02-01_11-45-42](https://user-images.githubusercontent.com/11411852/73589590-1e9e9700-44e9-11ea-9ecf-aca02a922ad6.png)

1. I use my version of [`.tmux.conf.local`](https://gist.github.com/Kira-Lappo/fd55c0669ece548940268dd929545ec1) instead of default one. Font: Courier New
![2020-02-01_11-47-06](https://user-images.githubusercontent.com/11411852/73589614-763d0280-44e9-11ea-8c83-ca3ff4edca27.png)

1. As you may notice Courier New doesn't really support Powerline glyphs. So I use [Cascadia Mono PL font by Microsoft](https://github.com/microsoft/cascadia-code). You may use any other Powerline font.
![2020-02-01_11-47-39](https://user-images.githubusercontent.com/11411852/73589638-ce740480-44e9-11ea-8445-d0eb07ec903f.png)

**Comment by tianxingyang** [comment]
> @tianxingyang
> ok, here we go, ultimate oh-my-tmux installation from scratch
> 
> 1. By default tmux looks like this. Font: Courier New
>    ![2020-02-01_11-43-03](https://user-images.githubusercontent.com/11411852/73589573-f1ea7f80-44e8-11ea-9270-f53eb166f052.png)
> 2. After installing oh-my-tmux by steps from README file. Font: Courier New
>    ![2020-02-01_11-45-42](https://user-images.githubusercontent.com/11411852/73589590-1e9e9700-44e9-11ea-9ecf-aca02a922ad6.png)
> 3. I use my version of [`.tmux.conf.local`](https://gist.github.com/Kira-Lappo/fd55c0669ece548940268dd929545ec1) instead of default one. Font: Courier New
>    ![2020-02-01_11-47-06](https://user-images.githubusercontent.com/11411852/73589614-763d0280-44e9-11ea-8c83-ca3ff4edca27.png)
> 4. As you may notice Courier New doesn't really support Powerline glyphs. So I use [Cascadia Mono PL font by Microsoft](https://github.com/microsoft/cascadia-code). You may use any other Powerline font.
>    ![2020-02-01_11-47-39](https://user-images.githubusercontent.com/11411852/73589638-ce740480-44e9-11ea-8445-d0eb07ec903f.png)
> 
> You can choose how to display battery status in `.tmux.conf.local` file.

thanks a lot :)

**Comment by Kira-Lappo** [comment]
@gpakosz consider closing the issue, @lucamaraschi liked you comment anyway

**Comment by lucamaraschi** [comment]
@Kira-Lappo thanks the issue was resolved for me too

**Comment by mr-j0nes** [comment]
It would be good to add this in the documentation's section for WSL
