### ISSUE TITLE
The status bar is not rendering properly!

### ISSUE THREAD

**Issue by yguo33** [gpakosz/.tmux#296]
<img width="1680" alt="截屏2019-11-05下午4 18 15" src="https://user-images.githubusercontent.com/11401434/68190387-3f3d7a80-ffe8-11e9-8465-38a8b8c4e83a.png">

**Comment by lucamaraschi** [comment]
Same issue here on Windows - WSL

**Comment by chendley** [comment]
Still working properly on Linux (Solus 4), for reference. Haven't tried macOS yet.

**Comment by artemZholus** [comment]
same problem on ubuntu

**Comment by cujomalainey** [comment]
I think mine broke when I upgraded tmux in brew `tmux 3.0 -> 3.0a`

**Comment by gpakosz** [comment]
I'm addressing @yguo33's original question here.

Looking at the screenshot, it seems "not rendering properly" is caused by the fact you didn't follow the step to have a `~/.tmux.conf.local` copy. When `~/.tmux.conf.local` was missing, default values were broken but it's fixed in `master` with commit 489cde73fcddde1a84f622aaf81d09c23ae655a5

**Comment by cujomalainey** [comment]
In response to my comment, turns out if you upgrade tmux and refresh your config without restarting your server then bad things happen

**Comment by gpakosz** [comment]
@yguo33 👋 does my comment above answer your initial question?

**Comment by yguo33** [comment]
@gpakosz I tried as you said and it works perfectly now:
`git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .
tmux kill-server
`

**Comment by gpakosz** [comment]
@yguo33 Great! I let you close the issue if you believe we're good
