### ISSUE TITLE
Maximising pane to new window does not work in fish

### ISSUE THREAD

**Issue by seowalex** [gpakosz/.tmux#328]
Maximising a pane to a new window doesn't seem to work in fish. It does open a new window with the previous contents of the pane that I'm trying to maximise, but it shows "Unable to maximise pane" at the bottom, and the pane that I tried to maximise gets removed in the original window.

**Comment by gpakosz** [comment]
Hello @seowalex,

Works for me.
I launched `fish`, then within `fish` I launched `tmux -L test` so that I'm in another session and there I could create windows and paths and was able to maximize panes.


Can you try to modify `.tmux.conf`? And change `retry=10` to `retry=100` or `retry=1000`?

Can you try the same with changing `sleep 0.05` to `sleep 0.1`?

**Comment by seowalex** [comment]
I have tried modifying the `.tmux.conf` as suggested. Both `retry=100` and `retry=1000` seem to work, though there is a noticeable delay. Changing `sleep 0.05` to `sleep 0.1` does not work, but after more testing, `sleep 0.2` works but still results in an "Unable to maximise pane" message, and `sleep 0.3` works with a similar delay to `retry=100` and `retry=1000`.

**Comment by gpakosz** [comment]
Yeah WSL makes a difference. On Windows forking is notoriously slow.

**Comment by seowalex** [comment]
I see. Would you advise increasing the number of retries or the sleep duration?

**Comment by gpakosz** [comment]
I will raise the retry count. It's just a sentinel to avoid looping forever

**Comment by gpakosz** [comment]
Can you please try the `gh-328` branch?

**Comment by seowalex** [comment]
That seems to have fixed it, cheers!

**Comment by gpakosz** [comment]
For the record, WSL2 is smoother but requires Windows Insider builds
