### ISSUE TITLE
I had a problem just after installing .tmux

### ISSUE THREAD

**Issue by g1thub-h** [gpakosz/.tmux#332]
![图片](https://user-images.githubusercontent.com/49114731/77058151-ff63b680-6a0f-11ea-8452-3a9cfee25b0c.png)
![图片](https://user-images.githubusercontent.com/49114731/77058157-02f73d80-6a10-11ea-8584-89bc41876f65.png)
![图片](https://user-images.githubusercontent.com/49114731/77058180-0db1d280-6a10-11ea-9202-7cadf6b5f328.png)

As shown in the figure, when I start Tmux, the message bar first prompts an error, and then my input box disappears. 

I reinstalled it many times without solving it. My system version is Ubuntu 18.04 x64 and the software version is Tmux 3.1-rc3. 

Please help me, I have found a lot of methods that have not been solved, this really bothers me

**Comment by gpakosz** [comment]
Hello @g1thub-h 👋

> when I start Tmux, the message bar first prompts an error

This is not an error message. It's what tmux displays when the system is slow. Looking at your screenshots I suspect the slowness comes from WSL which is notoriously slow.

> and then my input box disappears.

This is because tmux refreshed the status line. Very often, this is caused by tmux and your terminal emulator disagreeing on Unicode character widths.

---
Please give the `optimizations` branch a try. This will mitigate the `... not ready` messages but won't solve your terminal emulator vs tmux problems though. For that you can try to remove emojis or non ascii symbols from the status line. But every display problem is solely caused by tmux vs your terminal emulator. Not this configuration.

**Comment by g1thub-h** [comment]
Thanks for your help, I found out that I use TMUX on different terminals. There will be different results. 

There will be different degrees of exceptions in CMD and PowerShell, as shown in the figure. 
![图片](https://user-images.githubusercontent.com/49114731/77099690-52109300-6a4f-11ea-8b83-8872f1333f9c.png)

But it can be displayed normally in mobaxterm and vs code.
Is this a repairable place?

**Comment by gpakosz** [comment]
No idea sorry

**Comment by g1thub-h** [comment]
Thanks for your help.
