### ISSUE TITLE
change prefix to Alt+A

### ISSUE THREAD

**Issue by nguxx** [gpakosz/.tmux#336]
Hi,
Hoping to get a prefix with Alt+a, I tried different way to change C-a to M-a in the .tmux.conf.local... whithout succes (on Ubuntu)
You guessed I'm a n00b in tmux.
Would it be possible to have Alt+a as a prefix ? It's easier to do than C-a
BTW i love your config 
Thanx (from Paris ;)

**Comment by gpakosz** [comment]
Hello @nguxx 👋

Outside the terminal emulator side, you want to make sure your terminal emulator sends the proper escape codes to tmux. Launch `cat -v` then press `ALT + a` and you should see `^[a` in the output:
```
$ cat -v
^[a
```

On the tmux side, you need to edit your `~/.tmux.conf.local` copy so that it contains:
```
set -g prefix M-a
bind M-a send-prefix
```

Then you need to restart tmux or reload the configuration:
```
$ tmux source ~/.tmux.conf
```

**Comment by gpakosz** [comment]
@nguxx 👋

Did you manage to use `Alt` + `A` for prefix?

**Comment by nguxx** [comment]
@gpakosz 

For a reason I cannot understand i do not get `^[a` when I press ALT+a 
The crazy thing is that I can get `^[z^[q^[w^[w` or `^A`
but no `^[a` :astonished:
so I used 
```
set -g prefix M-q
bind M-q send-prefix
```
and ALT+q works like a charm...

**Comment by gpakosz** [comment]
> For a reason I cannot understand i do not get ^[a when I press ALT+a

Likely your terminal emulator intercepts `ALT` + `a`.

I let you close the issue if you believe we're good.

**Comment by nguxx** [comment]
Alt + A seems to be a issue of my computer, 2 different OS give the same result.

> I let you close the issue if you believe we're good.

Yes! perfect for me many thanks
