### ISSUE TITLE
WSL的tmux中Ctrl+Shift选中内容，无法滚动上下文

### ISSUE THREAD

**Issue by hongdada** [gpakosz/.tmux#388]
WSL2的tmux中Ctrl+Shift选中内容，无法滚动上下文

**Comment by gpakosz** [comment]
Hello @hongdada 👋

Please ask your question in English

**Comment by mstr3336** [comment]
Without translating, I can already guess @ this issue, and it's a problem with the WSL terminal, not your tmux.conf 

I adapted your tmux conf for my own dotfiles (but not the bindings), and one of my personal bindings is `C-Arrow`  to navigate panes w/o the prefix. 

When I tried to use my dotfiles on Windows:

On the WSL terminal, it just doesn't register `C-Arrow`, for whatever reason.

This was a big enough deal for me to not really want to use the WSL terminal, eventually I found that I was able to get everything I needed from cygwin's mintty terminal, with a cygwin X server ssh'd into WSL or vagrant boxes 

There are other reasons why sometimes modifier combos don't work, (xterm-keys on + binding to xterm key escapes helps- I don't know if this config already addresses that stuff), but WSL is likely the problem here.

**Comment by gpakosz** [comment]
The thing is: there's no such thing as the "WSL terminal" 🤷‍♂️

You either use mintty, Windows console or Windows Terminal Preview.

In any case sounds like a general tmux question.

**Comment by mstr3336** [comment]
Out of curiousity (I'm strugging to find a clear answer via google), what is the default terminal emulator that launches when you install, say "Ubuntu 20.04" from the microsoft store, and then launch it via the icon? 

Would it be windows console? Or mintty?

**Comment by gpakosz** [comment]
Pretty sure it's Windows Console
