### ISSUE TITLE
How to add current git branch to bottom bar

### ISSUE THREAD

**Issue by gpares** [gpakosz/.tmux#534]
How to add which branch im on in github on the bottom left?

**Comment by mircsicz** [comment]
+1 for me ;-)

**Comment by yuhaos** [comment]
I have the same requirement.
Could this tmux configuration support adding git branch information in powerline?

**Comment by jpcirrus** [comment]
Until then you can add it yourself, plus a lot more repository state information if you want, using [gitmux](https://github.com/arl/gitmux).

**Comment by gpakosz** [comment]
Hello there 👋

Sorry for the late reply.
I won't add new variables for Git because it would mean rewriting `__git_ps1` or any other Git integration that comes with your shell.

That being said, it's easy enough to add a custom `#{git_branch}` variable in your `~/.tmux.conf.local` copy:
```
# git_branch() {
#   cd "$1" && { git symbolic-ref -q --short HEAD || git rev-parse --short HEAD; }
# }
```

And you can use e.g. this way
```
tmux_conf_theme_status_right="#{git_branch #{pane_current_path}}"
```

Or as @jpcirrus mentioned, you can use a TPM plugin

**Comment by gpakosz** [comment]
Closing with this updated suggestion

You can add a `git_branch()` function to your `.local` customization file copy:
```
# git_branch() {
#   cd "${1:-$(tmux display -p '#{pane_current_path}')}" && { git symbolic-ref -q --short HEAD || git describe --tags --exact-match HEAD || git rev-parse --short HEAD; }
# }
```

Then you can e.g. update `tmux_conf_theme_status_left` or `tmux_conf_theme_status_right` to e.g.
```
tmux_conf_theme_status_right="#{git_branch #{pane_current_path} #{pane_id}}"
```

Which calls `git_branch()` with `2` arguments: `#{pane_current_path}` and `#{pane_id}`.
The second argument is unused by the `git_branch()` function itself but makes tmux re-evaluate the function when switching pane.

Finally, I decided against providing this solution as an official example because when `cd`ing in or out a Git work tree, the name of the branch won't be updated until tmux refreshes the status line. And by default Oh my tmux! sets `status-interval` to `10` seconds. You can solve this by customizing `cd` to make it refresh the tmux status line after changing directory, by e.g. adding the following function to your `.basrc` or `.zshrc`
```
cd() { builtin cd "$@" && "$TMUX_PROGRAM" -S "$TMUX_SOCKET" refresh-client -S }
```
