### ISSUE TITLE
Question: Where to edit window tab colors?

### ISSUE THREAD

**Issue by pauljacobson** [gpakosz/.tmux#548]
I'm enjoying this configuration, and I've been adapting it for my purposes. I noticed that when I have more than two windows open, the background color of the window names is pretty close to the text, and I can't see them clearly, like this:

![tmux_window_tabs_colors](https://user-images.githubusercontent.com/2912202/149782972-100e3f52-5056-4d9b-bff9-62e75b0dc2b0.png)

❓ Where can I edit these colors?

I'm still learning how to use tmux, and find my way around the Oh my tmux configuration. I'm unsure where to change these colors for these window tabs/labels. I'd appreciate any pointers!

**Comment by gpakosz** [comment]
Hello @pauljacobson 👋

Make sure you have properly configured your `~/.tmux.conf.local` copy, then
- Hit `<prefix> + e` which will open your default editor (`EDITOR` environment variable) to make you edit `~/.tmux.conf.local`
- Start with editing the `tmux_conf_theme_colour_...` variables
- Either you'll be satisfied with it, or alternatively edit the `tmux_conf_theme_window_...` variables to your liking
  - I'm not sure which variable is reponsible for the problem as it depends on bell and activity
- Upon quitting, it will automatically reload the configuration

Alternatively, edit your `~/.tmux.conf.local` copy and reload the configuration with `<prefix> + r`.

BTW, with the stock `.tmux.conf.local` file, do you have problems with colors?

PS: Thanks for the sponsorship, much appreciated!

**Comment by pauljacobson** [comment]
Hi there @gpakosz 

Thank you for your feedback!

>I'm not sure which variable is reponsible for the problem as it depends on bell and activity

Would you mind explaining further what you mean by this (or even pointing me to the docs where I can read more about this myself?

>BTW, with the stock .tmux.conf.local file, do you have problems with colors?

No, not at all. I just like using the `Ayu Mirage` color scheme, and have it installed in Neovim and iTerm2.

Just relating to the colors, the `ansi` color options have named colors:

```
# default theme (ansi)
#tmux_conf_theme_colour_1="colour0"
#tmux_conf_theme_colour_2="colour8"
#tmux_conf_theme_colour_3="colour8"
#tmux_conf_theme_colour_4="colour14"
#tmux_conf_theme_colour_5="colour11"
#tmux_conf_theme_colour_6="colour0"
#tmux_conf_theme_colour_7="colour15"
#tmux_conf_theme_colour_8="colour0"
#tmux_conf_theme_colour_9="colour11"
#tmux_conf_theme_colour_10="colour13"
#tmux_conf_theme_colour_11="colour10"
#tmux_conf_theme_colour_12="colour8"
#tmux_conf_theme_colour_13="colour15"
#tmux_conf_theme_colour_14="colour0"
#tmux_conf_theme_colour_15="colour0"
#tmux_conf_theme_colour_16="colour1"
#tmux_conf_theme_colour_17="colour15"
```

I just grabbed this from a template for illustration purposes. Is there a way to see what the named colors refer to? For example, which colour is `colour15`? If I look at my iTerm2 preferences, for example, I see this:

![ansi_colors](https://user-images.githubusercontent.com/2912202/149943920-4d9ac1e2-dec8-4f5d-8b22-9ea87b79a3fc.png)

There are colours for my theme variant on https://github.com/ayu-theme/ayu-colors although I'm unsure whether these correlate with the named colours in anyway. 🤔

**Comment by gpakosz** [comment]
When I say
> I'm not sure which variable is responsible for the problem as it depends on bell and activity

It means that at first you have somewhat 2 couples of `fg, bg` colors:
- for the current window "tab"
- for the non current windows "tab"

But then you can customize things further to
- color the last window "tab" differently
- color the window "tab" differently when the bell rings in a window
- color the window "tab" differently when there's activity in a non current window

---

Here I'm assuming you uncommented the `# default theme (ansi)` section so that `tmux_conf_theme_colour_...` variables use named colors in your `~/.tmux.conf.local` copy:
```
# default theme (ansi)
tmux_conf_theme_colour_1="colour0"
tmux_conf_theme_colour_2="colour8"
tmux_conf_theme_colour_3="colour8"
tmux_conf_theme_colour_4="colour14"
tmux_conf_theme_colour_5="colour11"
tmux_conf_theme_colour_6="colour0"
tmux_conf_theme_colour_7="colour15"
tmux_conf_theme_colour_8="colour0"
tmux_conf_theme_colour_9="colour11"
tmux_conf_theme_colour_10="colour13"
tmux_conf_theme_colour_11="colour10"
tmux_conf_theme_colour_12="colour8"
tmux_conf_theme_colour_13="colour15"
tmux_conf_theme_colour_14="colour0"
tmux_conf_theme_colour_15="colour0"
tmux_conf_theme_colour_16="colour1"
tmux_conf_theme_colour_17="colour15"
```
I assigned `tmux_conf_theme_colour_X` to `colourY` based on the default ANSI colors indexedx from `0` to `15, see https://en.wikipedia.org/wiki/ANSI_escape_code

![image](https://user-images.githubusercontent.com/553208/149961809-326b4729-0041-4aff-bcb2-05e6b494ee48.png)

And I set `tmux_conf_theme_colour_5="colour11"` so that it corresponds to yellow. And so that other colors match the default Oh my tmux! colorscheme.

But as you're experimenting, your iTerm2 theme redefines these colors
- "Normal" colors, in the left column, are colors from `0` to `7`
- "Bright" colors, in the right columns, are colors from `8` to `15`

And in your theme, `colour15` is white.

Now, should we look at
```
tmux_conf_theme_window_status_fg="$tmux_conf_theme_colour_3"
tmux_conf_theme_window_status_bg="$tmux_conf_theme_colour_1"
```
Since you have `tmux_conf_theme_colour_3="colour8"` and `tmux_conf_theme_colour_1="colour0"`, looking at your iTerm2 colors now you understand why Oh my tmux! uses gray on dark gray for the non current window "tabs".

At that point, I suggest you adjust `tmux_conf_theme_colour_...` and set them to other `colourXX` values.

To somewhat "fix" that, it looks like I will have to experiment with a couple of themes so that I choose colors that look good, while deviating from the default Oh my tmux! colorscheme.

**Comment by pauljacobson** [comment]
Thank you @gpakosz 

> But as you're experimenting, your iTerm2 theme redefines these colors
> 
> * "Normal" colors, in the left column, are colors from `0` to `7`
> * "Bright" colors, in the right columns, are colors from `8` to `15`
> 
> And in your theme, `colour15` is white.

This is what I was missing. I didn't understand that this is how the named colors work. Thank you for taking the time to explain this to me. I appreciate it.

**Comment by gpakosz** [comment]
> Thank you for taking the time to explain this to me. I appreciate it.

No problem. Are we good?

**Comment by pauljacobson** [comment]
Yes, thank you.

**Comment by sneko** [comment]
@pauljacobson did you use RGB at the end, or did you switch the mapping? If so, could you indicate the change to have something more readable please :) ?

Thank you,

**Comment by pauljacobson** [comment]
Hi there @sneko 

Thanks for the reminder. I wound up using this to set the colors in tmux:

```
# -- display -------------------------------------------------------------------

# RGB 24-bit colour support (tmux >= 2.2), possible values are:
#  - true
#  - false (default)
tmux_conf_24b_colour=false

# default theme
tmux_conf_theme_colour_1="#080808"    # dark gray
tmux_conf_theme_colour_2="#303030"    # gray
tmux_conf_theme_colour_3="#8a8a8a"    # light gray
tmux_conf_theme_colour_4="#00afff"    # light blue
tmux_conf_theme_colour_5="#ffff00"    # yellow
tmux_conf_theme_colour_6="#080808"    # dark gray
tmux_conf_theme_colour_7="#e4e4e4"    # white
tmux_conf_theme_colour_8="#080808"    # dark gray
tmux_conf_theme_colour_9="#ffff00"    # yellow
tmux_conf_theme_colour_10="#ff00af"   # pink
tmux_conf_theme_colour_11="#5fff00"   # green
tmux_conf_theme_colour_12="#8a8a8a"   # light gray
tmux_conf_theme_colour_13="#e4e4e4"   # white
tmux_conf_theme_colour_14="#080808"   # dark gray
tmux_conf_theme_colour_15="#080808"   # dark gray
tmux_conf_theme_colour_16="#d70000"   # red
tmux_conf_theme_colour_17="#e4e4e4"   # white
```
