### ISSUE TITLE
macOS Sierra and iTerm Problems

### ISSUE THREAD

**Issue by LockeAG** [gpakosz/.tmux#60]
As is describe here : https://github.com/gpakosz/.tmux/issues/39

it is happening to me:

ZSH: Antigen
Theme: https://github.com/sindresorhus/pure
iTerm: Build 3.1.20170323-nightly
TMUX: tmux 2.3
macOS: Sierra 10.12.3

![Screen1](http://i.imgur.com/PJuX3qK.png)

![Screen2](http://i.imgur.com/OxCGjI8.png)

**Comment by gpakosz** [comment]
Can you please try the `upcoming` branch?

**Comment by LockeAG** [comment]
@gpakosz  thank you for the answer , but nope , seame issue persist:

![Screen3](http://i.imgur.com/undefined.png)

**Comment by gpakosz** [comment]
From your screenshot, there's a lot of spacing after the `↑` and `↓` arrows. The problem is likely caused by terminal emulator and tmux disagreeing on Unicode symbols' width.

I'm not using ZSH but I'm using iTerm2 `Build 3.1.20170323-nightly`. Make sure you uncheck "Use Unicode version 9 character widths":

![image](https://cloud.githubusercontent.com/assets/553208/24285748/f638cbae-1071-11e7-91c8-00d9d8f54d57.png)

**Comment by LockeAG** [comment]
Great @gpakosz ! that worked!

Thank you!
