### ISSUE TITLE
error message: "GitHub doesn't seem to be reachable, skipping installing and/or updating tpm and plugins"

### ISSUE THREAD

**Issue by owenstake** [gpakosz/.tmux#703]
When I start tmux, error message appear as follows in tmux:
```bash
GitHub doesn't seem to be reachable, skipping installing and/or updating tpm and plugins"
```
And the `~/.config/tmux/plugins` is empty

I usually use `export all_proxy=http://xxx:xx` to proxy http/https request, but if fails for tmux with oh-my-tmux.

**Comment by gpakosz** [comment]
Hello @owenstake,

I don't know what the `all_proxy` environment variable is. According to a quick Google search it seems to be related to Gnome.

If you see the "`GitHub doesn't seem to be reachable, skipping installing and/or updating tpm and plugins`" message, it's because the `git` command can't reach GitHub.

Does the following command succeed outside of tmux and Oh my tmux!?
```
$ git ls-remote -hq https://github.com/gpakosz/.tmux.git master
```
