### ISSUE TITLE
${TERM} always set to tmux-256color, how to change it

### ISSUE THREAD

**Issue by QiMingZhenFan** [gpakosz/.tmux#731]
Thanks for your work!

I am using `zsh` & `tmux` in Ubuntu 18.04. Ouside tmux, the TERM is `xterm-256color`. However, inside tmux TERM is `tmux-256color`，eventhough I set `set -g default-terminal "xterm-256color"` in ~/.tmux.conf.local. 

![screenshot-20240314-175328](https://github.com/gpakosz/.tmux/assets/38323127/f9054e9a-0479-40c5-a3af-1270c6891abb)

I restart tmux by `tmux kill-server`, but nothing changes. BTW,  `set -g default-terminal "screen-256color"` doesn't work yet.

Is there something wrong with my usage? I want to change ${TERM} to `screen-256color` or `xterm-256color`, because  glog does not support outputing colored words in `tmux-256color`.

**Comment by gpakosz** [comment]
Hello @QiMingZhenFan 👋

You need to either
- Troubleshoot why `tmux-256color` doesn't work for you, as Oh my tmux! detects it and decides to use it
- Use `set -g default-terminal xterm-256color #!important` in your `.local` customization file

**Comment by gpakosz** [comment]
This is because the `.local` file is used for `2` purposes

- Defining `tmux_conf_...` variables
- Overriding bindings

When the top level `.conf` file is sourced, it then sources the `.local` file to know the values of the `tmux_conf_...` variables, then proceeds with customizing tmux: in this case, it detects that `tmux-256color` is available and decides to use it. It also updates some bindings. Finally, it scans the `.local` file again for `set`, `bind` and `unbind` directives marked with `#!important` (inspired by CSS), and applies these in a last pass.
