### ISSUE TITLE
Okular crashes with segmentation fault when opened inside tmux

### ISSUE THREAD

**Issue by thanhnguyenhy234** [gpakosz/.tmux#771]
Description:

When I open Okular outside of tmux, it runs normally without any issues. However, when I open Okular inside a tmux session, it crashes with the following error:

20332 segmentation fault (core dumped)

Environment:

    Okular version: okular 24.08.3
    OS: Archlinux

Additional Information:

    The error persists after restarting tmux and the system.

Would appreciate any guidance or fixes for this issue. Thanks!

![image](https://github.com/user-attachments/assets/fe44f6ba-adb8-40bc-8193-71756d4ff0f1)

If I run tmux kill-server and then restart tmux, Okular opens normally inside tmux. However, this only works after restarting tmux manually and does not resolve the issue after the initial system reboot.

**Comment by gpakosz** [comment]
Hello @thanhnguyenhy234 👋

I had no idea what Okular was before reading this issue.

I'm pretty sure the crash you're facing happens without using Oh my tmux!

Blind guess: if the crash really only happens when using Oh my tmux!, then I would try to add the following line to your `.local` customization file:
```
set -g default-terminal "screen-256color" #!important
```


In any case please reach out to the Okular project or the tmux project for a proper fix.
