### ISSUE TITLE
Can't change window

### ISSUE THREAD

**Issue by cirelli94** [gpakosz/.tmux#80]
I'm using tmux with your .tmux, I installed it using your instruction.
All is working nice but I can't change window with CTRL+B,N ! 
I can do it with CTRL+B,W.
I don't know how I can help to investigate this bug...
I'm using Guake and zsh.

**Comment by gpakosz** [comment]
Hello @cirelli94, this configuration [explicitly unbinds `<prefix> + n` and `<prefix> + p`.](https://github.com/gpakosz/.tmux/blob/264a577ba183bf7ce74da22a18fbb1bdba8244bf/.tmux.conf#L75-L76)

I believe I did that because [I wanted to use `<prefix> + p` for paste.](https://github.com/gpakosz/.tmux/blob/264a577ba183bf7ce74da22a18fbb1bdba8244bf/.tmux.conf#L120)

You can edit your own `~/.tmux.conf.local` copy and add
```
bind p previous-window
bind n next-window
```

**Comment by cirelli94** [comment]
ooooooooh thank you!

**Comment by a-eid** [comment]
@gpakosz try to 
```
bind p previous-window
bind n next-window
``` 
but still not working for some reason.

**Comment by gpakosz** [comment]
Hello 👋

You need to reload the configuration.

**Comment by hiiwave** [comment]
It would be great if it's described in the readme, as people might not expected it.
It takes me sometime to find out this issue and solve this.
Btw thanks for this awesome config!
