### ISSUE TITLE
How make  tmux_conf_copy_to_os_clipboard=true?

### ISSUE THREAD

**Issue by zxdposter** [gpakosz/.tmux#85]
I use this in my .zshrc file

    export tmux_conf_copy_to_os_clipboard=true

but is invalid.
What should I do ?

**Comment by gpakosz** [comment]
> What should I do?

Read [Installation](https://github.com/gpakosz/.tmux/blob/264a577ba183bf7ce74da22a18fbb1bdba8244bf/README.md#installation) instructions 🤣

```
$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
```

Now edit your `~/.tmux.conf.local` copy and set `tmux_conf_copy_to_os_clipboard` to `true`. You also need to have `reattach-to-user-namespace` installed otherwise processes within `tmux` can't communicate with the OS clipboard.

**Comment by zxdposter** [comment]
.... I am so stupid, I thinking set in .zshrc file...thanksss..

**Comment by gpakosz** [comment]
No problem 😀

So I guess it works for you?

On my side, I need to find a way to better communicate that installing my conf either implies restarting `tmux` (even the server process) or reloading/sourcing `~/.tmux.conf`.

**Comment by zxdposter** [comment]
I understand now😏
