### ISSUE TITLE
Can't get powerline to work with Bash On Windows

### ISSUE THREAD

**Issue by hlwrocer** [gpakosz/.tmux#86]
I've been trying to get powerline patched fonts to work with Bash on Windows, but uncommenting out the symbols in .tmux.conf.local seems to just break everything.

Starting up TMUX it shows me
![image](https://user-images.githubusercontent.com/8906127/27052342-6a6c8674-4f87-11e7-97f6-c6697a7773a3.png)
and it only happens when using a font prepatched with powerline symbols. Using a font that does not support the symbols just shows a filler ? character, and does not generate any errors.

and then this ends up happening.
![image](https://user-images.githubusercontent.com/8906127/27052358-7bcb4b94-4f87-11e7-875d-1bc4eeed1741.png)

I've been trying to figure out why this is happening, but haven't gotten anywhere with it.

**Comment by gpakosz** [comment]
For a start, if you're not using [`wsltty`](https://github.com/mintty/wsltty), please follow the [Troubleshooting](https://github.com/gpakosz/.tmux/blob/264a577ba183bf7ce74da22a18fbb1bdba8244bf/README.md#troubleshooting) section of `README.md`. Windows' console doesn't support `bold` or `blink` modifiers so you need to edit your `~/.tmux.conf.local` copy to remove them in all variables controlling look and feel.


Otherwise, here's a screenshot of me using `wsltty` + `Source Code Pro`

**Comment by hlwrocer** [comment]
Thanks, I would have preferred not to use wsltty since I'll be getting a new machine relatively soon, and didn't want to go through the trouble of setting this up again, but it appears its the best option until support for those modifiers arrive.

Thanks

**Comment by gpakosz** [comment]
Well, now there's an [installer](https://github.com/mintty/wsltty/releases). It's really click and forget.

**Comment by hlwrocer** [comment]
I tried doing that, but it ended up removing all the color as well. I guess I'll just stick with wsltty for now.
